import "./craw";
import "./upgrade-contract.task";
import "./mint-test-nft";
import "./launch-default-nft";
import "./get-contract-size";
import "./verify-default-nft";
import "./create-test-vote";
import "./new-gauge";
import "./distribute-test-coins";